### ISSUE TITLE
Release up to date version

### ISSUE THREAD

**Issue by saulshanabrook** [heavyai/jupyterlab-heavyai#96]
We should release an up to date version, at least with the parts we still need out of this.

The viz part now lives in https://github.com/quansight/ibis-vega-transform

So far, it seems like we at least need to also release the SQL editor widget. 

I will break this up into a number of packages, so it's easier to keep each up to date. Please comment if there is other things you are currently using from this package.

**Comment by mikehinchey** [comment]
Also this is old: https://anaconda.org/conda-forge/omnisci-pytools

**Comment by niviksha** [comment]
@saulshanabrook the SQL Editor widget is probably the main one. i did like the magics we had too, if there's a way to resurrect these it would be terrific.
